import { Injectable } from '@angular/core';

const url = "/assets/images/";

enum img {
  img1 = '/assets/images/ter_stegen_details.png',
  img2 = '/assets/images/neto_details.png'
}

const equipo: Array<any> = [
  // Goalkeepers
  { id: 1, number: 1, name: "Marc-André", surname: "Ter Stegen", backName: "Stegen", img: url + 'ter_stegen.png', position: "goalkeeper", games: 327, cleanSheets: 121, saves: 767, detailsImg: img.img1, bioTitleEn: 'A keeper with great reflexes and also excellent with the ball at his feet', bioTextEn:'Marc-André ter Stegen signed for FC Barcelona in the summer of 2014 from Borussia Mönchengladbach. Born on 30 April 1992 in Mönchengladbach itself, the German did not take long to make his name as one Europe’s most promising young goalkeepers.' , bioTitleEs: 'Portero sobrio y con grandes reflejos, destaca por el control aéreo y el dominio del juego de pies', bioTextEs: 'Marc-André ter Stegen firma como portero del FC Barcelona en verano de 2014 procedente del Borussia Mönchengladbach. Nacido el día 30 de abril de 1992 en la localidad de Mönchengladbach, el alemán despuntaba desde muy joven como uno de los porteros más prometedores del continente europeo.', bioImg: url + 'ter_stegen_bio.png' },
  { id: 2, number: 13, name: "Neto", surname: "", backName: "Neto", img: url + 'neto.png', position: "goalkeeper", games: 21, cleanSheets: 6, saves: 42, detailsImg: img.img2, bioTitleEn: 'His height, almost two metres, combined with his agility makes Neto a formidable presence between the posts', bioTextEn:'Norberto Murara "Neto" (Araxá, July 19, 1989) has speed and movement that has allowed him to defend his goal with security and deliver outstanding performances for Valencia (2017-2019), Juventus (2015-2017), Fiorentina (2011 -2015) and Paranaense (2002-2011).' , bioTitleEs: 'Su altura y agilidad lo convierten en un portero que reduce la amplitud de la portería', bioTextEs: 'Norberto Murara "Neto" (19 de julio de 1989) se convierte en azulgrana el 27 de junio de 2019. Antes de su llegada al Barça, este portero nacido en Araxá había encadenado actuaciones destacadas en la portería del Valencia (2017-2019), de la Juventus (2015-2017), de la Fiorentina (2011-2015) y del Paranaense (2002-2011). Guardameta desde pequeño en su tierra natal, siempre se ha enfundado los guantes emulando a su padre.', bioImg: url + 'neto_bio.png'  },
  // Defenders
  { id: 3, number: 2, name: "Sergiño", surname: "Dest", backName: "Dest", img: url + 'dest.png', position: "defender", games: 72, goals: 3, assists: 4, detailsImg: url + 'dest_details.png', bioTitleEn: 'Pacey right sided defender who likes to get forward', bioTextEn:'On 1 October 2020, Ajax and FC Barcelona reached an agreement on the transfer of Sergiño Dest, a 19-year-old right back with strong prospects for the future and who had thoroughly impressed in the Dutch championship in 2019/20.' , bioTitleEs: 'Lateral derecho ofensivo, irrumpe mucho en ataque pero también corrige rápido su posición. Su velocidad hace que sea un defensor difícil de superar', bioTextEs: 'El 1 de octubre de 2020, Ajax y FC Barcelona llegan a un acuerdo para el traspaso de Sergiño Dest. Con 19 años, pues, y una gran proyección de futuro, el lateral derecho aterriza en Barcelona tras consolidarse en el equipo holandés durante la temporada 2019/20.', bioImg: url + 'dest_bio.png' },
  { id: 4, number: 3, name: "Gerard", surname: "Piqué", backName: "Piqué", img: url + 'pique.png', position: "defender", games: 606, goals: 52, assists: 7, detailsImg: url + 'pique_details.png', bioTitleEn: "Considered one of the best centre halves in the world, Gerard Piqué brings together character, class and strength in the air', bioTextEn:'Gerard Piqué was born on 2 February 1987 and since that day he has been a club member of FC Barcelona. Since he was very young he has been involved with the club and when he was 10 years old he joined the youngest boys' team at the club at that time (U12 B)." , bioTitleEs: 'Uno de los mejores centrales del mundo, reúne carácter, clase y un poderoso juego aéreo también en ataque', bioTextEs: 'Gerard Piqué nace en Barcelona el 2 de febrero de 1987, y desde ese mismo día es socio del club. De muy pequeño ingresa en el torneo social del FC Barcelona y con 10 años se inicia en el fútbol base en la primera de las categorías que existían en ese momento, el Alevín B.', bioImg: url + 'pique_bio.png' },
  { id: 5, number: 4, name: "Ronald", surname: "Araújo", backName: "Araújo", img: url + 'araujo.png', position: "defender", games: 82, goals: 6, assists: 1, detailsImg: url + 'araujo_details.png', bioTitleEn: 'Uruguayan defender, strong in the air and capable with the ball at his feet', bioTextEn:'Ronald Araujo was born in Rivera, Uruguay, on 7 March 1999. The young central defender began playing professionally for his hometown team, and later joined the lower categories at Rentistas in the Uruguayan Second Division.' , bioTitleEs: 'Central uruguayo con proyección, con buena salida de balón y dominio del juego aéreo', bioTextEs: 'Ronald Araujo nació en Rivera, Uruguay, el 7 de marzo de 1999. El joven defensa central da sus primeros pasos como profesional en el equipo de su ciudad, y luego ingresa a las categorías inferiores del Rentistas, equipo de la Segunda División de Uruguay.', bioImg: url + 'araujo_bio.png' },
  { id: 6, number: 18, name: "Jordi", surname: "Alba", backName: "Alba", img: url + 'jordi_alba.png', position: "defender", games: 428, goals: 25, assists: 85, detailsImg: url + 'jordi_alba_details.png', bioTitleEn: 'As quick as anyone, Jordi Alba is recognised as one of the most attacking left backs in modern football', bioTextEn:'Jordi Alba signed for FC Barcelona on 5 July 2012 after the Club had reached an agreement with Valencia for his transfer. The Catalan defender was 23 when he joined the Club and was the first signing of the 2012/13 season.' , bioTitleEs: 'Rápido y hábil, aprovecha su técnica para incorporarse al ataque por la banda izquierda', bioTextEs: 'En 2012, procedente del Valencia CF, Jordi Alba Ramos vuelve al FC Barcelona en su segunda etapa como jugador azulgrana. Nacido en Hospitalet de Llobregat el 21 de marzo de 1989, el lateral ya había estado durante más de siete años en las categorías inferiores del Barça.', bioImg: url + 'jordi_alba_bio.png' },
  { id: 7, number: 22, name: "Óscar", surname: "Mingueza", backName: "Mingueza", img: url + 'oscar_mingueza.png', position: "defender", games: 66, goals: 2, assists: 5, detailsImg: url + 'oscar_mingueza_details.png', bioTitleEn: 'A strong ball-playing central defender', bioTextEn:'Òscar Mingueza was born on May 13, 1999 in Santa Perpètua de Mogoda, a municipality in the Vallès Occidental region of Catalonia. The centre-back has played at every level for Barça, from U7 through to Barça B. His debut with the B team came on July 27, 2016, in a friendly match against Llagostera, however, it wasn’t until the 2018/19 season that he became a full-time member of the squad.' , bioTitleEs: 'Defensa central que aporta solidez defensiva y que tiene una buena salida de balón', bioTextEs: 'Òscar Mingueza nació el 13 de mayo de 1999 en Santa Perpètua de Mogoda, un municipio del Vallès Occidental. El central se ha vestido toda la vida de azulgrana, desde el Prebenjamín hasta el Barça B. Con el filial culé debutó el 27 de julio de 2016 en un partido amistoso contra el Llagostera. Pero hasta la temporada 2018/19 no ha pasado a formar parte del filial.', bioImg: url + 'oscar_mingueza_bio.png' },
  { id: 8, number: 23, name: "Samuel", surname: "Umtiti", backName: "Umtiti", img: url + 'samuel_umtiti.png', position: "defender", games: 133, goals: 2, assists: 1, detailsImg: url + 'samuel_umtiti_details.png', bioTitleEn: 'The French international, at the Club since 2016, is known for his physical strength, his ability to anticipate, and his prowess in getting the ball up the field', bioTextEn:"Samuel Umtiti came to FC Barcelona to reinforce the team's defensive line. The Cameroon-born Frenchman landed in Barcelona on 14 July 2016 from Olympique Lyonnais, where he was a regular in the starting eleven" , bioTitleEs: 'Destaca por su potencia física, su capacidad de anticipación y su buena salida de baló', bioTextEs: 'Samuel Umtiti ficha por el FC Barcelona el 14 de julio de 2016 para reforzar la línea defensiva del equipo de Luis Enrique. El francés de origen camerunés aterriza procedente del Olympique de Lyon.', bioImg: url + 'samuel_umtiti_bio.png' },
  { id: 9, number: 24, name: "Eric", surname: "García", backName: "García", img: url + 'eric_garcia.png', position: "defender", games: 36, goals: 0, assists: 0, detailsImg: url + 'eric_garcia_details.png', bioTitleEn: 'Centre back who excels at getting the ball out from the back and has an instinctive ability to read the game', bioTextEn:'Eric Garcia returned to Barça in the summer of 2021 from Manchester City. He originally joined the Barça Escola in 2008 and resided at La Masia until 2017.' , bioTitleEs: 'Central con buena salida del balón y una gran inteligencia a la hora de anticiparse a sus rivales, comprende el juego de forma instintiva', bioTextEs: 'Eric Garcia vuelve al Barça en verano de 2021 procedente del Manchester City. El central ingresa en la Barça Escola en 2008 y se cría en la Masia hasta 2017.', bioImg: url + 'eric_garcia_bio.png' },
  { id: 10, number: 0, name: "Andreas", surname: "Christensen", backName: "Christensen", img: url + 'andreas_christensen.png', position: "defender", games: 0, goals: 0, assists: 0, detailsImg: url + 'andreas_christensen_details.png', bioTitleEn: 'Centre back with brilliant passing skills and a tremendous reading of the game. Fabulous and finding the right route to get the ball forward', bioTextEn:'An excellent reader of the game and versatile centre back, Andreas Christensen (10 April 1996) was born in Lillerød (Denmark) where he started out at IF Skjold Birkerød, soon catching the eye of Brøndby IF.' , bioTitleEs: 'Central con gran salida de pelota y buena lectura defensiva. Destaca por sus pases que rompen las líneas de presión', bioTextEs: 'Andreas Christensen (10 de abril de 1996) nació en Allerød (Dinamarca) donde empezó a jugar a fútbol en el IF Skjold Birkerød. Su progresión y buen rendimiento hizo que se fijara en él el Brøndby IF.', bioImg: url + 'andreas_christensen_bio.png' },
  // Midfielders
  { id: 11, number: 5, name: "Sergio", surname: "Busquets", backName: "Busquets", img: url + 'sergio_busquets.png', position: "midfielder", games: 681, goals: 18, assists: 36, detailsImg: url + 'sergio_busquets_details.png', bioTitleEn: 'Sergio Busquets is probably the best defensive midfielder in the world. He stands out for his technical ability and his unsurpassed reading of the game', bioTextEn:'Born in Sabadell, he joined the Barça youth system in the summer of 2005 from Jabac. That season, playing for the U19A side, he won three major trophies alongside the likes of Bojan Krkic, Giovani, Jeffren and Marc Crosas.' , bioTitleEs: 'Su técnica y la excepcional lectura táctica lo hacen el mejor medio centro defensivo del mundo', bioTextEs: 'Nacido en Sabadell el 16 de julio de 1988, el hijo de Carlos Busquets, portero del FC Barcelona en los años 90, llega al fútbol formativo del Barça en verano de 2005 procedente del Jàbac. Aquella temporada, con el Juvenil A, consigue el triplete con un equipo en el que también juegan Bojan, Giovani, Jeffren y Marc Crosas, entre otros.', bioImg: url + 'sergio_busquets_bio.png' },
  { id: 12, number: 6, name: "Riqui", surname: "Puig", backName: "Puig", img: url + 'riqui_puig.png', position: "midfielder", games: 57, goals: 2, assists: 3, detailsImg: url + 'riqui_puig_details.png', bioTitleEn: 'Riqui Puig is a creative midfielder with a great vision of the game and great skill', bioTextEn:'Riqui Puig started at Barça in the Under-16 category, coming from Jàbac Terrassa. At La Masia he improved as a player and has grown steadily through the categories. He made his debut with Barça B against the Gimnàstic Tarragona in the 2017/18 season. His performance with the reserves marveled the fans and he became the undisputed star of that game. For the 2018/19 season, he is playing for Barça B.' , bioTitleEs: 'Riqui Puig es un medio creativo con una visión privilegiada del juego y una gran calidad', bioTextEs: 'Riqui Puig empezó su camino en el Barça en la categoría cadete, procedente del Jàbac y Terrassa. En la Masía ha potenciado su calidad y ha crecido futbolísticamente pasando paso a paso por las categorías inferiores, donde suma la UEFA Youth League de la temporada 2017/2018, superando al Chelsea en la final (3-0), como su éxito más importante. Debutó con el Barça B, de la mano de Gerard López, en el partido contra el Gimnàstic de Tarragona la temporada 2017/18. Su actuación con el filial maravilló a los aficionados y se convirtió en el protagonista indiscutible de aquel partido. La temporada 2018/19 pasa a formar parte del Barça B, mientras que en el inicio de la 2020/21 sube al primer equipo.', bioImg: url + 'riqui_puig_bio.png' },
  { id: 13, number: 8, name: "Pedri", surname: "", backName: "Pedri", img: url + 'pedri_gonzalez.png', position: "midfielder", games: 74, goals: 9, assists: 7, detailsImg: url + 'pedri_gonzalez_details.png', bioTitleEn: 'The player enjoys playing on the front foot, driving at his direct opponent and having his passes break the defensive lines', bioTextEn:"On September 2, 2019, FC Barcelona and Las Palmas reached an agreement for the transfer of Pedri. However, the Canarian player didn't join the blaugranes until August 2020. Born in Tegueste, Tenerife, on November 25, 2002, he began his football career in the team from his hometown." , bioTitleEs: 'Gusto por el fútbol combinativo, el joven futbolista tiene una excelente conducción del balón y sus milimétricos pases rompen líneas defensivas', bioTextEs: 'El 2 de septiembre de 2019, el FC Barcelona y Las Palmas llegan a un acuerdo para el traspaso de Pedri. Pero el jugador canario no se incorpora al equipo culé hasta agosto del 2020. Nacido en Tegueste, Tenerife, el 25 de noviembre de 2002, el canario inicia su carrera futbolística en el equipo de su localidad natal.', bioImg: url + 'pedri_gonzalez_bio.png' },
  { id: 14, number: 14, name: "Nico", surname: "González", backName: "González", img: url + 'nico_gonzalez.png', position: "midfielder", games: 37, goals: 2, assists: 2, detailsImg: url + 'nico_gonzalez_details.png', bioTitleEn: 'A ball playing midfielder who is tactically astute', bioTextEn:'Nico González arrived at FC Barcelona at the age of 11 from Montañeros, after Barça scouts had seen him play in a friendly in Galicia. His progress since then has been spectacular. He began to shine in the Under-14s B team which were proclaimed league champions in the 2013/14 season, also winning titles for the club in 2015/16, 2016/17, 2017/18 and 2019/20 as he made his way up the ranks.' , bioTitleEs: 'Interior con marcado estilo Barça que destaca por su inteligencia táctica', bioTextEs: 'Nico González llegó al fútbol formativo del FC Barcelona a los 11 años procedente del Montañeros, después que los entrenadores azulgranas lo vieran jugar en un amistoso disputado en Galicia. Desde entonces su progresión ha sido espectacular. Se trata de un interior, con marcado ADN Barça, que empezó a brillar con el Infantil B de Marcel Sans que se proclamó campeón de Liga la temporada 2013/14. Ha pasado por todas las categorías del fútbol formativo azulgrana y destaca, por ejemplo, su participación en la consecución de los títulos de Liga con el Cadete B (2015/16), el Cadete A (2016/17 y 2017/18) y el Juvenil A (2019/20).', bioImg: url + 'nico_gonzalez_bio.png' },
  { id: 15, number: 20, name: "Sergi", surname: "Roberto", backName: "Roberto", img: url + 'sergi_roberto.png', position: "midfielder", games: 316, goals: 12, assists: 37, detailsImg: url + 'sergi_roberto_details.png', bioTitleEn: 'Sergi Roberto is one of the most versatile players in the squad and is known for his ability to get into the box', bioTextEn:'When Sergi Roberto was 14 years old he traded the town of Reus for La Masia. The ex-Nàstic Tarragona midfielder improved year after year until he became a crucial player for Luis Enrique’s Barça B team.' , bioTitleEs: 'Futbolista polivalente que brilla por su inteligencia, técnica y capacidad de asociación', bioTextEs: 'Con 14 años Sergi Roberto, nacido el 7 de febrero de 1992, abandona Reus para pisar con fuerza en la Masia del FC Barcelona. Procedente del Nàstic de Tarragona, el centrocampista se va consolidando etapa tras etapa hasta convertirse en una pieza fija en el esquema del filial dirigido por Luis Enrique, equipo con el que debuta la temporada 2009/10.', bioImg: url + 'sergi_roberto_bio.png' },
  { id: 16, number: 21, name: "Frenkie", surname: "de Jong", backName: "Jong", img: url + 'frenkie_deJong.png', position: "midfielder", games: 140, goals: 13, assists: 15, detailsImg: url + 'frenkie_deJong_details.png', bioTitleEn: 'His versatility, energy and great vision have allowed him to continue developing his skills in any midfield position', bioTextEn:'Frenkie de Jong was born in Arkel (Netherlands) on May 12, 1996. The Barça player started his career at Willem II in the Eredivise, the Dutch first division. In 2016 he signed for Ajax, where he gradually gained a place in the starting eleven. His versatility and his great vision allowed him to become the midfield organiser for the team from Amsterdam.' , bioTitleEs: 'Visión de juego, gran cabalgata y polivalencia en cualquier posición del centro del campo', bioTextEs: 'Frenkie de Jong nace en Arkel (Países Bajos) el 12 de mayo de 1996. El holandés llega al Barça en verano de 2019 después de una gran campaña con el Ajax de Amsterdam, consolidándose ya como un centrocampista de presente y futuro.', bioImg: url + 'frenkie_deJong_bio.png' },
  { id: 17, number: 0, name: "Franck", surname: "Kessié", backName: "Kessié", img: url + 'frank_kessie.png', position: "midfielder", games: 0, goals: 0, assists: 0, detailsImg: url + 'frank_kessie_details.png', bioTitleEn: 'A very strong midfielder with a tremendous shot and ability to win the ball back', bioTextEn:"A powerful midfielder who is excellent defensively and can get forward and score goals, Franck Kessie was born in Ivory Coast on December 19, 1996. He set out on his football career at Stella Club d'Adjamé in his home country." , bioTitleEs: 'Centrocampista con un gran físico, golpeo de pelota y habilidad para recuperar balones perdidos', bioTextEs: 'Franck Kessie nació en Costa de Marfil el 19 de diciembre de 1996. En su país natal empezó a jugar a fútbol en Stella Club de Adjamé.', bioImg: url + 'frank_kessie_bio.png' },
  // Forwards
  { id: 18, number: 7, name: "Ousmane", surname: "Dembélé", backName: "Dembélé", img: url + 'ousmane_dembele.png', position: "forward", games: 150, goals: 32, assists: 33, detailsImg: url + 'ousmane_dembele_details.png', bioTitleEn: 'The French winger is one of most exciting dribblers in football and thrives on troubling rival defences both for club and country', bioTextEn:'At the end of 2014 he signed his first professional contract with French club Rennes. He made his Ligue 1 debut at just the age of 17 and he scored his first goal against Girondins. His progress attracted the attention of Borussia Dortmund and he signed for the Bundesliga club in the summer of 2016. Dembélé adapted quickly to German football, scoring 12 goals and providing 20 assists in his first season.' , bioTitleEs: 'El extremo francés es uno de los futbolistas con más capacidad de desequilibrio y regate en el fútbol mundial', bioTextEs: 'Nacido el 15 de mayo de 1997 en Vernon (Francia), el extremo llegó al FC Barcelona el 25 de agosto de 2017 con sólo 20 años, después de haber demostrado en la liga francesa y en la liga alemana que era uno de los futbolistas con mayor capacidad de desequilibrio y regate en el fútbol mundial. Posteriormente, el 14 de julio de 2022, firma la ampliación de su contrato hasta 2024.', bioImg: url + 'ousmane_dembele_bio.png' },
  { id: 19, number: 9, name: "Memphis", surname: "Depay", backName: "Depay", img: url + 'memphis_depay.png', position: "forward", games: 38, goals: 13, assists: 2, detailsImg: url + 'memphis_depay_details.png', bioTitleEn: 'Versatile striker, who not only scores but also likes to contribute to the build-up', bioTextEn:'The Dutchman signed for Barça in the summer of 2021 after playing previously in the Eredivisie, Premier League and Ligue 1. Born 3 February 1994 in Moordrecht (Holland), Memphis Depay is more than the usual striker' , bioTitleEs: 'Atacante polivalente. Lejos de ser un delantero exclusivamente de área, le gusta participar en el juego', bioTextEs: 'El holandés ficha por el Barça en verano de 2021, después de hacer carrera en la Eredivisie, la Premier League y la Ligue 1. Nacido el 3 de febrero de 1994 a Moordrecht (Holanda), Memphis Depay es más que un delantero puro.', bioImg: url + 'memphis_depay_bio.png' },
  { id: 20, number: 10, name: "Ansu", surname: "Fati", backName: "Fati", img: url + 'ansu_fati.png', position: "forward", games: 58, goals: 19, assists: 3, detailsImg: url + 'ansu_fati_details.png', bioTitleEn: 'Instinct, speed and skill. Ansu Fati is the chosen heir of our number 10', bioTextEn:'Anssumane Fati (31 October 2002) was born in Bissau, the capital of Guinea Bissau. The striker moved to Seville at the age of six where he began in the youth team set up at Sevilla. In 2012, at the age of 10, he joined the FC Barcelona youth teams before making his debut with the first team in the 2019/20 season.' , bioTitleEs: 'Gol, velocidad y desequilibrio. Ansu Fati es el elegido heredero del dorsal 10 culé', bioTextEs: 'Anssumane Fati (31 de octubre de 2002) nació en Bissau, la capital de Guinea Bissau. El delantero llegó a Sevilla con seis años, donde jugó en las categorías inferiores del Sevilla FC. En 2012, con sólo 10 años, Ansu aterrizó en el conjunto azulgrana para incorporarse al Alevín A, donde fue pasando por las diversas categorías inferiores del FC Barcelona hasta llegar al primer equipo.', bioImg: url + 'ansu_fati_bio.png' },
  { id: 21, number: 12, name: "Martin", surname: "Braithwaite", backName: "Braithwaite", img: url + 'martin_braithwaite.png', position: "forward", games: 58, goals: 10, assists: 4, detailsImg: url + 'martin_braithwaite_details.png', bioTitleEn: 'The forward brings much more than goals as the Dane can play anywhere up front', bioTextEn:'Born on 5 June 1991 in the port city of Esbjerg, Denmark, Martin Braithwaite Christensen started out in the academy at Sædding-Guldager Idrætsforening, after which he joined the biggest club in his city Esbjerg fB, and four years later switched the blue-and-white of EfB for the violet of Toulouse in France. Braithwaite slowly made his mark at TFC, scoring 35 goals in Ligue 1 before changing club and country once again, this time joining Middlesbrough, who were in the English Championship at the time.' , bioTitleEs: "La aportación de este delantero va más allá de los goles. Porque este '9', que también puede actuar en los lados del ataque, es trabajo y voluntad", bioTextEs: 'El 20 de febrero de 2020, el Barça hace efectiva la cláusula de rescisión del jugador Martin Braithwaite, que así queda desvinculado de la disciplina del Club Deportivo Leganés y viaja para Barcelona.', bioImg: url + 'martin_braithwaite_bio.png' },
  { id: 22, number: 19, name: "Ferran", surname: "Torres", backName: "Torres", img: url + 'ferran_torres.png', position: "forward", games: 26, goals: 7, assists: 6, detailsImg: url + 'ferran_torres_details.png', bioTitleEn: 'He brings together various talents which allow him to operate anywhere up front', bioTextEn:'Born on 29 February 2000 in Foios (Valencia), Ferran Torres made first contact with the ball at an early age. He started out with futsal at the EPLA school and then attracted the attention of the Valencia CF academy. He was only seven years when he wore the shirt for the first time.' , bioTitleEs: 'Puede ocupar cualquier posición ofensiva, exhibiendo velocidad, verticalidad, calidad e inteligencia', bioTextEs: 'Nacido el 29 de febrero del 2000 en Foios (Valencia), Ferran Torres empezó con el fútbol sala en la escuela EPLA y llamó la atención de la cantera del Valencia CF. Con sólo siete años, inició su trayectoria vistiendo la elástica valencianista.', bioImg: url + 'ferran_torres_bio.png' },
  { id: 23, number: 25, name: "Pierre-Emerick", surname: "Aubameyang", backName: "Aubameyang", img: url + 'pierreEmerick_aubameyang.png', position: "forward", games: 23, goals: 13, assists: 1, detailsImg: url + 'pierreEmerick_aubameyang_details.png', bioTitleEn: 'Experienced goalscorer, he has the pace to get behind defences and find space', bioTextEn:'Born in Laval (Mayenne, France) on 18 June 1989, Pierre-Emerick Aubameyang has triple nationality: Spanish, French and Gabonese, but plays internationally for Gabon. The striker has experience of playing in several European countries.' , bioTitleEs: 'Delantero consagrado y con amplia experiencia, destaca por su capacidad de romper líneas con desmarcadas al espacio que le permiten sacar provecho de su gran punta de velocidad', bioTextEs: 'Después de pasar por el fútbol base de distintos equipos, el del AC Milan incluido, Francia fue el país donde Aubameyang dio el salto al fútbol profesional. Anotando goles con las camisetas del Dijon (2008/09), Lille (2009/10), AS Mónaco (2010/11) y Saint Etienne, su buen nivel hizo que un histórico de Europa lo reclutara por sus filas.', bioImg: url + 'pierreEmerick_aubameyang_bio.png' },
  { id: 24, number: 0, name: "Raphinha", surname: "", backName: "Raphinha", img: url + 'raphinha.png', position: "forward", games: 0, goals: 0, assists: 0, detailsImg: url + 'raphinha_details.png', bioTitleEn: 'A technically gifted, skill winger with great dribbling skills and combination play', bioTextEn:'Raphael Dias Belloli (Raphinha) was born on 14 December 1996 in Porto Alegre, Brazil. He joined the Club from Leeds United in summer 2022.' , bioTitleEs: 'Extremo técnico con mucha habilidad para regatear y combinar', bioTextEs: 'Raphael Dias Belloli (Raphinha) nació el 14 de diciembre de 1996 en Porto Alegre, Brasil. El jugador llega al Club en verano de 2022 procedente del Leeds United.', bioImg: url + 'raphinha_bio.png' },
  { id: 25, number: 0, name: "Robert", surname: "Lewandowski", backName: "Lewandowski", img: url + 'robert_lewandowski.png', position: "forward", games: 0, goals: 0, assists: 0, detailsImg: url + 'robert_lewandowski_details.png', bioTitleEn: "One of the best strikers ever, the Polish forward's stats speak for themselves", bioTextEn:"The striker from Poland stands out for his goalscoring abilities. Inside the box he has all the tools to make him a difficult striker to read as he can find the net with his head and both feet with equal precision." , bioTitleEs: 'Es uno de los mejores delanteros de la historia del fútbol. El ariete polaco tiene unas estadísticas goleadoras de escándalo tanto en Alemania como en Europa', bioTextEs: 'En verano de 2022, Lewandowski decide abandonar la disciplina del Bayern de Múnich, equipo en el que estuvo ocho temporadas, y se incorpora al FC Barcelona. De esta forma, el club azulgrana se hace con un delantero histórico, que tiene unas estadísticas anotadoras de escándalo tanto en Alemania como en Europa. De hecho, Lewandowski llega a Barcelona entre los cinco futbolistas que más goles han anotado en la historia de la Champions League y como el segundo máximo goleador de la historia de la Bundesliga.', bioImg: url + 'robert_lewandowski_bio.png' },
  // Coach
  { id: 579849, number: 0, name: "Xavi", surname: "", backName: "Xavi", img: url + 'xavi_hernandez.png', position: "coach", games: 0, goals: 0, assists: 0 },
];

@Injectable({
  providedIn: 'root'
})
export class PlayersService {

  constructor() { }

  getPlayerById(id: number) {
    return equipo.find((player) => {
      if (player.id == id) {
        return player;
      }
    })
  }

  getAllPlayers() {
    return equipo.filter((player) => {
        return player;
    })
  }

  getGoalkeepers() {
    return equipo.filter((player) => {
      if (player.position === "goalkeeper") {
        return player;
      }
    })
  }

  getDefenders() {
    return equipo.filter((player) => {
      if (player.position === "defender") {
        return player;
      }
    })
  }

  getMidfielders() {
    return equipo.filter((player) => {
      if (player.position === "midfielder") {
        return player;
      }
    })
  }

  getForwards() {
    return equipo.filter((player) => {
      if (player.position === "forward") {
        return player;
      }
    })
  }

  getCoach() {
    return equipo.filter((coach) => {
      if (coach.position === "coach") {
        return coach;
      }
    })
  }
}
